### PR TITLE
Homebrew formula updates

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by str4d** [comment]
This is tested and working. However, due to how Homebrew works, these changes will be merged into the 0.10.0 formula update when that occurs.

**Comment by FiloSottile** [comment]
> This is tested and working. However, due to how Homebrew works, these changes will be merged into the 0.10.0 formula update when that occurs.

You can also add a `revision 1` line, canonically after the `version` line.

**Comment by str4d** [comment]
That's good to know for future changes, but most of the changes in this PR depend on code changes that are not part of a public release, and the Homebrew formulae unconditionally pins a specific published release that currently does not contain those changes.

**Comment by str4d** [comment]
Changes pushed to `main`.

**Pull request closed without merging**
