### PR TITLE
i18n-embed-fl 0.3

### PR DESCRIPTION
**Pull request by str4d**
Fixes an issue where `cargo update` breaks builds (due to how `i18n-embed-fl 0.2` was not pinning its pre-release `dashmap` dependency).

### CODE REVIEW

**Comment by str4d** [comment]
Ugh, there is something weird going on inside GitHub's Windows CI worker, that I can't yet recreate on my local Windows machine...

**Comment by str4d** [comment]
Hmm, this is probably https://github.com/kellpossible/cargo-i18n/issues/36...

**Comment by str4d** [comment]
Opened https://github.com/kellpossible/cargo-i18n/issues/57

**Comment by woodruffw** [comment]
Any chance for a patch release for this bump? `cargo install` doesn't (appear to) respect `Cargo.lock`, so attempting to `cargo install rage` (or any other application crate that uses `age`) errors out with:

```
   Compiling i18n-embed-fl v0.2.0
error[E0599]: no method named `insert_and_get` found for struct `DOMAINS` in the current scope
   --> /Users/william/.cargo/registry/src/github.com-1ecc6299db9ec823/i18n-embed-fl-0.2.0/src/lib.rs:360:17
    |
136 | / lazy_static::lazy_static! {
137 | |     /// Cached data specific to each localization domain, to improve
138 | |     /// performance of subsequent macro invokations.
139 | |     static ref DOMAINS: dashmap::DashMap<String, DomainSpecificData> =
140 | |         dashmap::DashMap::new();
141 | | }
    | |_- method `insert_and_get` not found for this
...
360 |           DOMAINS.insert_and_get(domain.clone(), data)
    |                   ^^^^^^^^^^^^^^ method not found in `DOMAINS`
```

(`cargo install --locked` works, but that's not the default, unfortunately...)

**Comment by str4d** [comment]
> `cargo install` doesn't (appear to) respect `Cargo.lock`

Wait what? This is not at all what I would expect from the way binary packages are described. I've replicated this behaviour locally.

I'll be cutting a release of `rage` in the next few days, so this will be resolved shortly, but I'm going to dig into what is going on here.

**Comment by woodruffw** [comment]
> Wait what? This is not at all what I would expect from the way binary packages are described. I've replicated this behaviour locally.

Yep :disappointed: -- this is currently intentional behavior in Cargo, at least according to https://github.com/rust-lang/cargo/issues/7169. The rationale seems to be that a build error is better than silently wrong behavior (assuming that a dependency is broken), but it occurs to me that it's just as likely for an updated dependency to have silently wrong behavior, leading to painful "works on my machine" debugging.

The fix is to use `--locked` to tell `cargo install` to respect the lockfile, but that *really* feels like it should be the default to me.

> I'll be cutting a release of `rage` in the next few days, so this will be resolved shortly, but I'm going to dig into what is going on here.

Sounds good! I know I've said it before, but thanks again for your work on `rage` + the `age` crate :slightly_smiling_face:

**Pull request merged**
